name: Website Availability Check

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs only on default branch automatically
  workflow_dispatch:  # Can be triggered manually on any branch

jobs:
  check-websites:
    runs-on: ubuntu-latest
    # Uncomment to restrict to specific branches:
    # if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Check websites
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_GROUP: ${{ secrets.TELEGRAM_GROUP }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          #!/bin/bash
          set -euo pipefail
          
          [[ ! -f "websites.json" ]] && { echo "ERROR: websites.json missing"; exit 1; }
          jq empty websites.json 2>/dev/null || { echo "ERROR: Invalid JSON"; exit 1; }
          
          CONFIG=$(jq -r '.settings // {}' websites.json)
          RETRIES=$(echo "$CONFIG" | jq -r '.retries // 3')
          TIMEOUT=$(echo "$CONFIG" | jq -r '.timeout // 10')
          
          NOTIF=$(jq -r '.notifications // {}' websites.json)
          TG_ON=$(echo "$NOTIF" | jq -r '.telegram.enabled // false')
          SLACK_ON=$(echo "$NOTIF" | jq -r '.slack.enabled // false')
          DISCORD_ON=$(echo "$NOTIF" | jq -r '.discord.enabled // false')
          
          notify() {
            local type=$1 name=$2 status=$3 url=$4 msg=${5:-}
            
            if [[ "$status" == "200" ]]; then
              return 0
            fi
            
            local alert="⚠️ $name is down!"
            [[ -n "$status" ]] && alert="$alert (HTTP $status)" || alert="$alert ($msg)"
            
            if [[ "$TG_ON" == "true" && -n "${TELEGRAM_TOKEN:-}" && -n "${TELEGRAM_GROUP:-}" ]]; then
              curl -sS -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
                -d "chat_id=${TELEGRAM_GROUP}" \
                -d "text=<b>$alert</b>%0A%0AURL: $url" \
                -d "parse_mode=HTML" &>/dev/null || true
            fi
            
            if [[ "$SLACK_ON" == "true" && -n "${SLACK_WEBHOOK:-}" ]]; then
              curl -sS -X POST "$SLACK_WEBHOOK" \
                -H "Content-Type: application/json" \
                -d "{\"text\":\"*$alert*\nURL: $url\"}" &>/dev/null || true
            fi
            
            if [[ "$DISCORD_ON" == "true" && -n "${DISCORD_WEBHOOK:-}" ]]; then
              curl -sS -X POST "$DISCORD_WEBHOOK" \
                -H "Content-Type: application/json" \
                -d "{\"content\":\"@here **$alert**\nURL: $url\"}" &>/dev/null || true
            fi
          }
          
          check_site() {
            local name=$1 url=$2
            echo "Checking $name..."
            
            for ((attempt=1; attempt<=RETRIES; attempt++)); do
              [[ $attempt -gt 1 ]] && { echo "  Retry $attempt/$RETRIES"; sleep 5; }
              
              response=$(curl -sS -w "\n%{http_code}" -H "User-Agent: Mozilla/5.0" \
                --max-time "$TIMEOUT" -L "$url" 2>&1) && {
                status="${response##*$'\n'}"
                echo "  Status: $status"
                [[ "$status" == "200" ]] && return 0
                notify "http" "$name" "$status" "$url"
                continue
              }
              
              case $? in
                28) error="Timeout after ${TIMEOUT}s" ;;
                7)  error="Connection refused" ;;
                6)  error="DNS resolution failed" ;;
                35) error="SSL error" ;;
                *)  error="Connection error (code $?)" ;;
              esac
              
              echo "  Failed: $error"
              notify "error" "$name" "" "$url" "$error"
            done
            
            return 1
          }
          
          echo "=== Website Availability Check ==="
          
          sites=$(jq -c '.websites[]' websites.json 2>/dev/null || echo "")
          [[ -z "$sites" ]] && { echo "No websites configured"; exit 0; }
          
          total=0 up=0
          
          while IFS= read -r site; do
            name=$(echo "$site" | jq -r '.name // ""')
            url=$(echo "$site" | jq -r '.URL // ""')
            
            [[ -z "$name" || -z "$url" ]] && continue
            
            total=$((total + 1))
            check_site "$name" "$url" && up=$((up + 1))
            echo
          done <<< "$sites"
          
          down=$((total - up))
          
          echo "=== Summary: $up/$total sites up ==="
          
          [[ $down -eq 0 ]] && exit 0
          [[ $up -eq 0 ]] && exit 2
          # exiting...
          exit 1